{"name": "test_vwo_login_negative", "status": "skipped", "statusDetails": {"message": "XFAIL reason: Failed\n\n_pytest.outcomes.XFailed: Failed", "trace": "self = <test_vmo_login_pom.TestLogin object at 0x00000229CB9D3680>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"bf4aec655f031f1117b4bab41f070dfa\")>\n\n    @allure.epic(\"VWO Login Test\")\n    @allure.feature(\"TC#0 - VWO App Negative Test\")\n    @pytest.mark.negative\n    @pytest.mark.usefixtures(\"setup\")\n    \n    def test_vwo_login_negative(self,setup):\n        try:\n            driver = setup\n            loginPage = LoginPage(driver)\n            loginPage.login_to_vwo(usr=\"admin@admin@gmail.com\", pwd=\"admin\")\n            time.sleep(5)\n            error_message = loginPage.get_error_message_text()\n>           assert error_message == \"Yours email, password, IP address or location did not match\"\nE           AssertionError: assert 'Your email, password, IP address or location did not match' == 'Yours email, password, IP address or location did not match'\nE             \nE             - Yours email, password, IP address or location did not match\nE             ?     -\nE             + Your email, password, IP address or location did not match\n\ntest_vmo_login_pom.py:29: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_vmo_login_pom.TestLogin object at 0x00000229CB9D3680>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"bf4aec655f031f1117b4bab41f070dfa\")>\n\n    @allure.epic(\"VWO Login Test\")\n    @allure.feature(\"TC#0 - VWO App Negative Test\")\n    @pytest.mark.negative\n    @pytest.mark.usefixtures(\"setup\")\n    \n    def test_vwo_login_negative(self,setup):\n        try:\n            driver = setup\n            loginPage = LoginPage(driver)\n            loginPage.login_to_vwo(usr=\"admin@admin@gmail.com\", pwd=\"admin\")\n            time.sleep(5)\n            error_message = loginPage.get_error_message_text()\n            assert error_message == \"Yours email, password, IP address or location did not match\"\n        except Exception as e:\n>           pytest.xfail(\"Failed\")\nE           _pytest.outcomes.XFailed: Failed\n\ntest_vmo_login_pom.py:31: XFailed"}, "start": 1744177650513, "stop": 1744177656554, "uuid": "c5448ec8-b29c-4c19-b8ce-7aec884b0fd3", "historyId": "69d752a7abe0ee8736382e42ae176568", "testCaseId": "69d752a7abe0ee8736382e42ae176568", "fullName": "tests.vmoLoginTests.pom_testclass.test_vmo_login_pom.TestLogin#test_vwo_login_negative", "labels": [{"name": "epic", "value": "VWO Login Test"}, {"name": "feature", "value": "TC#0 - VWO App Negative Test"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests.vmoLoginTests.pom_testclass"}, {"name": "suite", "value": "test_vmo_login_pom"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-AVQG3N0"}, {"name": "thread", "value": "14740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.vmoLoginTests.pom_testclass.test_vmo_login_pom"}]}