{"name": "test_vwo_login_negative", "status": "skipped", "statusDetails": {"message": "XFAIL reason: Failed\n\n_pytest.outcomes.XFailed: Failed", "trace": "self = <test_vmo_login_pom.TestLogin object at 0x00000249AD1A9550>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"01fd48108a5f059aa32765535dcac77d\")>\n\n    @allure.epic(\"VWO Login Test\")\n    @allure.feature(\"TC#0 - VWO App Negative Test\")\n    @pytest.mark.negative\n    @pytest.mark.usefixtures(\"setup\")\n    \n    def test_vwo_login_negative(self,setup):\n        try:\n            driver = setup\n            loginPage = LoginPage(driver)\n            loginPage.login_to_vwo(usr=\"admin@admin@gmail.com\", pwd=\"admin\")\n            time.sleep(5)\n>           error_message = loginPage.get_error_message_text()\n\ntest_vmo_login_pom.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\pageObjects\\loginPage.py:70: in get_error_message_text\n    return self.get_error_message().text\n..\\..\\pageObjects\\loginPage.py:48: in get_error_message\n    return self.driver.find_element(*LoginPage.error_message)\n..\\..\\..\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:898: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n..\\..\\..\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:429: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x00000249AD146E40>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"no such element: Unable to locate element: {\\...03133589+5465]\\\\n\\\\tBaseThreadInitThunk [0x00007FFF461AE8D7+23]\\\\n\\\\tRtlUserThreadStart [0x00007FFF47EDBF6C+44]\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"#js-notification-box-msg\"}\nE         (Session info: chrome=135.0.7049.42); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       \tGetHandleVerifier [0x00007FF603145335+78597]\nE       \tGetHandleVerifier [0x00007FF603145390+78688]\nE       \t(No symbol) [0x00007FF602EF91AA]\nE       \t(No symbol) [0x00007FF602F4F149]\nE       \t(No symbol) [0x00007FF602F4F3FC]\nE       \t(No symbol) [0x00007FF602FA2467]\nE       \t(No symbol) [0x00007FF602F7712F]\nE       \t(No symbol) [0x00007FF602F9F2BB]\nE       \t(No symbol) [0x00007FF602F76EC3]\nE       \t(No symbol) [0x00007FF602F403F8]\nE       \t(No symbol) [0x00007FF602F41163]\nE       \tGetHandleVerifier [0x00007FF6033EEEED+2870973]\nE       \tGetHandleVerifier [0x00007FF6033E9698+2848360]\nE       \tGetHandleVerifier [0x00007FF603406973+2967875]\nE       \tGetHandleVerifier [0x00007FF60316017A+188746]\nE       \tGetHandleVerifier [0x00007FF60316845F+222255]\nE       \tGetHandleVerifier [0x00007FF60314D2B4+111236]\nE       \tGetHandleVerifier [0x00007FF60314D462+111666]\nE       \tGetHandleVerifier [0x00007FF603133589+5465]\nE       \tBaseThreadInitThunk [0x00007FFF461AE8D7+23]\nE       \tRtlUserThreadStart [0x00007FFF47EDBF6C+44]\n\n..\\..\\..\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:232: NoSuchElementException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_vmo_login_pom.TestLogin object at 0x00000249AD1A9550>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"01fd48108a5f059aa32765535dcac77d\")>\n\n    @allure.epic(\"VWO Login Test\")\n    @allure.feature(\"TC#0 - VWO App Negative Test\")\n    @pytest.mark.negative\n    @pytest.mark.usefixtures(\"setup\")\n    \n    def test_vwo_login_negative(self,setup):\n        try:\n            driver = setup\n            loginPage = LoginPage(driver)\n            loginPage.login_to_vwo(usr=\"admin@admin@gmail.com\", pwd=\"admin\")\n            time.sleep(5)\n            error_message = loginPage.get_error_message_text()\n            assert error_message == \"Yours email, password, IP address or location did not match\"\n        except Exception as e:\n>           pytest.xfail(\"Failed\")\nE           _pytest.outcomes.XFailed: Failed\n\ntest_vmo_login_pom.py:31: XFailed"}, "attachments": [{"name": "stdout", "source": "6cdbdb15-6367-48c2-9225-a684332c0b62-attachment.txt", "type": "text/plain"}], "start": 1744178144828, "stop": 1744178149879, "uuid": "45adad02-2574-4f8a-93f5-0ee18d78cd72", "historyId": "69d752a7abe0ee8736382e42ae176568", "testCaseId": "69d752a7abe0ee8736382e42ae176568", "fullName": "tests.vmoLoginTests.pom_testclass.test_vmo_login_pom.TestLogin#test_vwo_login_negative", "labels": [{"name": "epic", "value": "VWO Login Test"}, {"name": "feature", "value": "TC#0 - VWO App Negative Test"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests.vmoLoginTests.pom_testclass"}, {"name": "suite", "value": "test_vmo_login_pom"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-AVQG3N0"}, {"name": "thread", "value": "20728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.vmoLoginTests.pom_testclass.test_vmo_login_pom"}]}